/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.uv.app.fq.init;

import cl.uv.app.fq.bo.MedicoBo;
import cl.uv.app.fq.bo.PacienteBo;
import cl.uv.app.fq.controller.Paciente;
import javax.swing.JButton;

/**
 *
 * @author bnavarro
 */
public class JFListarPaciente extends javax.swing.JFrame {

    private int conteoClick = 0;
    private MedicoBo medico;

    /**
     * Creates new form panel1
     *
     * @param medico
     */
    public JFListarPaciente(MedicoBo medico) {
        this.medico = medico;
        initComponents();
        this.setLocationRelativeTo(null);
        Paciente controller = new Paciente();
        controller.getAllPacientes(jTablePacientes);
    }

    private JFListarPaciente() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelListarPaciente = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePacientes = new javax.swing.JTable();
        lblNombrePaciente = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelListarPaciente.setBackground(new java.awt.Color(255, 255, 255));

        jTablePacientes.setBackground(new java.awt.Color(0, 204, 255));
        jTablePacientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTablePacientes.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        jTablePacientes.setForeground(new java.awt.Color(255, 255, 255));
        jTablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Paciente", "Edad", "Fecha Incorporación", "Perfil"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePacientes.setGridColor(new java.awt.Color(255, 255, 255));
        jTablePacientes.setMinimumSize(new java.awt.Dimension(120, 0));
        jTablePacientes.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jTablePacientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTablePacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePacientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePacientes);

        lblNombrePaciente.setBackground(new java.awt.Color(255, 255, 255));
        lblNombrePaciente.setFont(new java.awt.Font("Arial Unicode MS", 3, 18)); // NOI18N
        lblNombrePaciente.setForeground(new java.awt.Color(255, 255, 255));
        lblNombrePaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/uv/app/fq/resource/btns/pacientes inscriots.png"))); // NOI18N
        lblNombrePaciente.setOpaque(true);

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/uv/app/fq/resource/btns/BotonVolverAnadirPaciente.png"))); // NOI18N
        btnVolver.setBorder(null);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListarPacienteLayout = new javax.swing.GroupLayout(jPanelListarPaciente);
        jPanelListarPaciente.setLayout(jPanelListarPacienteLayout);
        jPanelListarPacienteLayout.setHorizontalGroup(
            jPanelListarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarPacienteLayout.createSequentialGroup()
                .addGroup(jPanelListarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListarPacienteLayout.createSequentialGroup()
                        .addComponent(lblNombrePaciente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelListarPacienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListarPacienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVolver)))
                .addContainerGap())
        );
        jPanelListarPacienteLayout.setVerticalGroup(
            jPanelListarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarPacienteLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblNombrePaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelListarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelListarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTablePacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePacientesMouseClicked
        int column = jTablePacientes.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / jTablePacientes.getRowHeight();
        Paciente pacienteController = new Paciente();
        if (row < jTablePacientes.getRowCount() && row >= 0 && column < jTablePacientes.getColumnCount() && column >= 0) {
            Object value = jTablePacientes.getValueAt(row, column);
            if (value instanceof JButton && conteoClick == 0) {
                conteoClick++;
                ((JButton) value).doClick();
                JButton boton = (JButton) value;
                boton.setEnabled(false);

                PacienteBo paciente = pacienteController.getPacienteWherId(boton.getName());

                JFPerfilPaciente panel = new JFPerfilPaciente(paciente, medico);
                panel.setVisible(true);
                this.setVisible(false);

            }

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTablePacientesMouseClicked

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
        JFHome jf = new JFHome(medico);
        jf.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFListarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFListarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFListarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFListarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFListarPaciente();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanelListarPaciente;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePacientes;
    private javax.swing.JLabel lblNombrePaciente;
    // End of variables declaration//GEN-END:variables
}
