/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.uv.app.fq.init;

import cl.uv.app.fq.bo.MedicoBo;
import cl.uv.app.fq.bo.PacienteBo;
import cl.uv.app.fq.controller.Control;
import cl.uv.app.fq.resource.ResourcesUtil;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author bnavarro
 */
public class JFPerfilPaciente extends javax.swing.JFrame {

    private PacienteBo paciente;
    private MedicoBo medico;

    /**
     * Creates new form JFPerfilPaciente
     *
     * @param paciente
     * @param medico
     */
    public JFPerfilPaciente(PacienteBo paciente, MedicoBo medico) {
        initComponents();
        this.setLocationRelativeTo(null);

        this.paciente = paciente;
        this.medico = medico;
        cargarLabel();
    }

    private JFPerfilPaciente() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void cargarLabel() {
        Control controlController = new Control();
        lblNombrePaciente.setText(paciente.getNombre());
        lblFechaNac.setText("Fecha de nacimiento: " + String.valueOf(paciente.getFechaNacimiento()));
        lblFechaIncor.setText("Fecha de incorporación: " + String.valueOf(paciente.getFechaIncorporacion()));
//        lbl.setText("Edad: " + getEdad(String.valueOf(paciente.getFechaNacimiento())));
        lblPesoInicial.setText(String.valueOf("Peso inicial: " + paciente.getPeso() + " Kl"));
        lblEstaturaInicial.setText(String.valueOf("Estatura inicial: " + paciente.getEstatura() + " Cm"));
//        textAreaComentarios.setText(paciente.getComentario());
        lvlNumeroControlesAsistidos.setText("N° Controles asistidos: " + String.valueOf(controlController.getCantidadControles(paciente)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnIniciarControl = new javax.swing.JButton();
        btnEstadisticaDeControl = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnEstadisticaDeJuego = new javax.swing.JButton();
        lblNombrePaciente = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnVolver1 = new javax.swing.JButton();
        lblFechaNac = new javax.swing.JLabel();
        lblFechaIncor = new javax.swing.JLabel();
        lblPesoInicial = new javax.swing.JLabel();
        lblEstaturaInicial = new javax.swing.JLabel();
        lvlNumeroControlesAsistidos = new javax.swing.JLabel();
        lblProximoControl = new javax.swing.JLabel();
        jDataFechaControl = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Perfil del paciente");

        btnIniciarControl.setBackground(new java.awt.Color(255, 255, 255));
        btnIniciarControl.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        btnIniciarControl.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/uv/app/fq/resource/btns/iniciar control.png"))); // NOI18N
        btnIniciarControl.setBorder(null);
        btnIniciarControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciarControl.setMaximumSize(new java.awt.Dimension(150, 29));
        btnIniciarControl.setMinimumSize(new java.awt.Dimension(150, 29));
        btnIniciarControl.setPreferredSize(new java.awt.Dimension(100, 29));
        btnIniciarControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarControlActionPerformed(evt);
            }
        });

        btnEstadisticaDeControl.setBackground(new java.awt.Color(255, 255, 255));
        btnEstadisticaDeControl.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        btnEstadisticaDeControl.setForeground(new java.awt.Color(255, 255, 255));
        btnEstadisticaDeControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/uv/app/fq/resource/btns/estadistica.png"))); // NOI18N
        btnEstadisticaDeControl.setBorder(null);
        btnEstadisticaDeControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstadisticaDeControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticaDeControlActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevo.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/uv/app/fq/resource/btns/recompensa.png"))); // NOI18N
        btnNuevo.setBorder(null);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/uv/app/fq/resource/btns/listarcontroles.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnEstadisticaDeJuego.setBackground(new java.awt.Color(255, 255, 255));
        btnEstadisticaDeJuego.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        btnEstadisticaDeJuego.setForeground(new java.awt.Color(255, 255, 255));
        btnEstadisticaDeJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/uv/app/fq/resource/btns/sesiones de juego.png"))); // NOI18N
        btnEstadisticaDeJuego.setBorder(null);
        btnEstadisticaDeJuego.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstadisticaDeJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticaDeJuegoActionPerformed(evt);
            }
        });

        lblNombrePaciente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNombrePaciente.setForeground(new java.awt.Color(0, 204, 255));
        lblNombrePaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombrePaciente.setText("Nombre del paciente");

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/uv/app/fq/resource/btns/botonvolver.png"))); // NOI18N
        btnVolver.setBorder(null);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnVolver1.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        btnVolver1.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/uv/app/fq/resource/btns/notificar.png"))); // NOI18N
        btnVolver1.setBorder(null);
        btnVolver1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver1ActionPerformed(evt);
            }
        });

        lblFechaNac.setBackground(new java.awt.Color(204, 204, 204));
        lblFechaNac.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblFechaNac.setForeground(new java.awt.Color(153, 153, 153));
        lblFechaNac.setText("Fecha de nacimiento:");
        lblFechaNac.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        lblFechaNac.setOpaque(true);

        lblFechaIncor.setBackground(new java.awt.Color(204, 204, 204));
        lblFechaIncor.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblFechaIncor.setForeground(new java.awt.Color(153, 153, 153));
        lblFechaIncor.setText("Fecha de incorporación:");
        lblFechaIncor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        lblFechaIncor.setOpaque(true);

        lblPesoInicial.setBackground(new java.awt.Color(204, 204, 204));
        lblPesoInicial.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblPesoInicial.setForeground(new java.awt.Color(153, 153, 153));
        lblPesoInicial.setText("Peso inicial:");
        lblPesoInicial.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        lblPesoInicial.setOpaque(true);

        lblEstaturaInicial.setBackground(new java.awt.Color(204, 204, 204));
        lblEstaturaInicial.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblEstaturaInicial.setForeground(new java.awt.Color(153, 153, 153));
        lblEstaturaInicial.setText("Estatura inicial:");
        lblEstaturaInicial.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        lblEstaturaInicial.setOpaque(true);

        lvlNumeroControlesAsistidos.setBackground(new java.awt.Color(204, 204, 204));
        lvlNumeroControlesAsistidos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lvlNumeroControlesAsistidos.setForeground(new java.awt.Color(153, 153, 153));
        lvlNumeroControlesAsistidos.setText("N° Controles asistidos:");
        lvlNumeroControlesAsistidos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        lvlNumeroControlesAsistidos.setOpaque(true);

        lblProximoControl.setBackground(new java.awt.Color(255, 255, 255));
        lblProximoControl.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblProximoControl.setForeground(new java.awt.Color(102, 102, 102));
        lblProximoControl.setText("Próximo control:");
        lblProximoControl.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFechaIncor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPesoInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEstaturaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lvlNumeroControlesAsistidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProximoControl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnVolver1)
                        .addComponent(jDataFechaControl, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNombrePaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnEstadisticaDeJuego)
                        .addComponent(jLabel2))
                    .addComponent(btnEstadisticaDeControl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIniciarControl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jButton1))
                    .addComponent(btnVolver, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEstadisticaDeJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnEstadisticaDeControl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIniciarControl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNombrePaciente)
                        .addGap(19, 19, 19)
                        .addComponent(lblFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFechaIncor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPesoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEstaturaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lvlNumeroControlesAsistidos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lblProximoControl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jDataFechaControl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVolver1)))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarControlActionPerformed
        JFIniciarControl panel = new JFIniciarControl(paciente, medico);
        panel.setVisible(true);
        this.setVisible(false);     // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarControlActionPerformed

    private void btnEstadisticaDeControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticaDeControlActionPerformed
        JFEstadistica panel = new JFEstadistica(paciente, medico);
        panel.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstadisticaDeControlActionPerformed

    private void btnEstadisticaDeJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticaDeJuegoActionPerformed

        JFListarSesionesJuego panel = new JFListarSesionesJuego(paciente, medico);
        panel.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnEstadisticaDeJuegoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        JFRecompensar panel = new JFRecompensar(paciente, medico);
        panel.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFListarControles panel = new JFListarControles(paciente, medico);
        panel.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
        JFListarPaciente jf = new JFListarPaciente(medico);
        jf.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        ResourcesUtil rutil = new ResourcesUtil();
        JOptionPane.showInputDialog(null, "Asunto: ", "Notificación", 1, new ImageIcon(rutil.getPulmonShowMessage()), null, null);
    }//GEN-LAST:event_btnVolver1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPerfilPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPerfilPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPerfilPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPerfilPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            JFPerfilPaciente jfPerfilPaciente = new JFPerfilPaciente();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstadisticaDeControl;
    private javax.swing.JButton btnEstadisticaDeJuego;
    private javax.swing.JButton btnIniciarControl;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnVolver1;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDataFechaControl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblEstaturaInicial;
    private javax.swing.JLabel lblFechaIncor;
    private javax.swing.JLabel lblFechaNac;
    private javax.swing.JLabel lblNombrePaciente;
    private javax.swing.JLabel lblPesoInicial;
    private javax.swing.JLabel lblProximoControl;
    private javax.swing.JLabel lvlNumeroControlesAsistidos;
    // End of variables declaration//GEN-END:variables
}
