/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.uv.app.fq.init;

import cl.uv.app.fq.bo.MedicoBo;
import cl.uv.app.fq.bo.PacienteBo;
import cl.uv.app.fq.controller.Paciente;
import cl.uv.app.fq.resource.ResourcesUtil;
import com.placeholder.PlaceHolder;
import java.awt.Color;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author bnavarro
 */
public class JPAnadirPaciente_old extends javax.swing.JFrame {

    private MedicoBo medico;

    /**
     * Creates new form panel1
     *
     * @param medico
     */
    public JPAnadirPaciente_old(MedicoBo medico) {
        initComponents();
        this.medico = medico;
        PlaceHolder holder = new PlaceHolder(txtNombre, "-");
        holder = new PlaceHolder(jSpinnerEstatura, "000.0");
        holder = new PlaceHolder(jSpinnerPeso, "00.0");
        holder = new PlaceHolder(jTextAreaComentarios, "Escriba un comentario...");
        jDateChooserIncorporacion.setBackground(Color.red);
    }

    private JPAnadirPaciente_old() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jDateChooserNacimiento = new com.toedter.calendar.JDateChooser();
        jDateChooserIncorporacion = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaComentarios = new javax.swing.JTextArea();
        btnAnadir = new javax.swing.JButton();
        jSpinnerPeso = new javax.swing.JTextField();
        jSpinnerEstatura = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnAnadir1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtNombre.setBackground(new java.awt.Color(204, 204, 204));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));

        jDateChooserNacimiento.setBackground(new java.awt.Color(204, 204, 204));
        jDateChooserNacimiento.setForeground(new java.awt.Color(255, 255, 255));

        jDateChooserIncorporacion.setBackground(new java.awt.Color(204, 204, 204));
        jDateChooserIncorporacion.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        jLabel6.setText("Comentarios");

        jScrollPane1.setRequestFocusEnabled(false);

        jTextAreaComentarios.setBackground(new java.awt.Color(204, 204, 204));
        jTextAreaComentarios.setColumns(20);
        jTextAreaComentarios.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaComentarios.setRows(5);
        jTextAreaComentarios.setPreferredSize(new java.awt.Dimension(160, 20));
        jScrollPane1.setViewportView(jTextAreaComentarios);

        btnAnadir.setBackground(new java.awt.Color(102, 102, 102));
        btnAnadir.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        btnAnadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadir.setText("Añadir");
        btnAnadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });

        jSpinnerPeso.setBackground(new java.awt.Color(204, 204, 204));
        jSpinnerPeso.setForeground(new java.awt.Color(255, 255, 255));
        jSpinnerPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jSpinnerPesoKeyReleased(evt);
            }
        });

        jSpinnerEstatura.setBackground(new java.awt.Color(204, 204, 204));
        jSpinnerEstatura.setForeground(new java.awt.Color(255, 255, 255));
        jSpinnerEstatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jSpinnerEstaturaKeyReleased(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/uv/app/fq/resource/btns/añadirpaciet.png"))); // NOI18N

        btnAnadir1.setBackground(new java.awt.Color(102, 102, 102));
        btnAnadir1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        btnAnadir1.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadir1.setText("Añadir");
        btnAnadir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnadir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserIncorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jDateChooserNacimiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSpinnerPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSpinnerEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnAnadir1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnadir1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jDateChooserNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jDateChooserIncorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jSpinnerPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(btnAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed

        String nombre = txtNombre.getText();

        Date dateNacimiento = jDateChooserNacimiento.getDate();
        Date dateIncorporacion = jDateChooserIncorporacion.getDate();

        float peso = Float.parseFloat(jSpinnerPeso.getText());
        float estatura = Float.parseFloat(jSpinnerEstatura.getText());

        String comentario = jTextAreaComentarios.getText();
        int medicoIdMedico = medico.getIdMedico();
        PacienteBo pacienteBo = new PacienteBo(0, nombre, dateNacimiento, dateIncorporacion, peso, estatura, comentario, medicoIdMedico);
        Paciente pacienteController = new Paciente();
        ResourcesUtil rutil = new ResourcesUtil();

        if (pacienteController.ingresaPaciente(pacienteBo, medico) == 1) {
            JOptionPane.showMessageDialog(null, "Paciente Agregado exitosamente!.", "Información:", 0, new ImageIcon(rutil.getPulmonShowMessage()));

            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();

            JPInicio panel = new JPInicio();
            jPanel1.add(panel);
            jPanel1.repaint();
            jPanel1.revalidate();
        } else {
            JOptionPane.showMessageDialog(null, "No se ha podido agregar paciente.", "Información:", 0, new ImageIcon(rutil.getPulmonShowMessage()));

        }

    }//GEN-LAST:event_btnAnadirActionPerformed

    private void jSpinnerPesoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerPesoKeyReleased
        String[] v = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "."};
        char c = evt.getKeyChar();
        String s = "%" + c;
        s = s.replace("%", "");
        if (s.equals(v[0]) || s.equals(v[1]) || s.equals(v[2]) || s.equals(v[3]) || s.equals(v[4]) || s.equals(v[5])) {
        } else if (s.equals(v[6]) || s.equals(v[7]) || s.equals(v[8]) || s.equals(v[9]) || s.equals(v[10])) {
        } else {
            int k = jSpinnerPeso.getText().length() - 1;
            String n = jSpinnerPeso.getText().substring(0, k);
            jSpinnerPeso.setText(n);
        }
    }//GEN-LAST:event_jSpinnerPesoKeyReleased

    private void jSpinnerEstaturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerEstaturaKeyReleased
        String[] v = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "."};
        char c = evt.getKeyChar();
        String s = "%" + c;
        s = s.replace("%", "");
        if (s.equals(v[0]) || s.equals(v[1]) || s.equals(v[2]) || s.equals(v[3]) || s.equals(v[4]) || s.equals(v[5])) {
        } else if (s.equals(v[6]) || s.equals(v[7]) || s.equals(v[8]) || s.equals(v[9]) || s.equals(v[10])) {
        } else {
            int k = jSpinnerEstatura.getText().length() - 1;
            String n = jSpinnerEstatura.getText().substring(0, k);
            jSpinnerEstatura.setText(n);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jSpinnerEstaturaKeyReleased

    private void btnAnadir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnadir1ActionPerformed
  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());

                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JPAnadirPaciente_old().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnAnadir1;
    private com.toedter.calendar.JDateChooser jDateChooserIncorporacion;
    private com.toedter.calendar.JDateChooser jDateChooserNacimiento;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSpinnerEstatura;
    private javax.swing.JTextField jSpinnerPeso;
    private javax.swing.JTextArea jTextAreaComentarios;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
