/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.uv.app.fq.init;

import cl.uv.app.fq.bo.MedicoBo;
import cl.uv.app.fq.bo.PacienteBo;
import cl.uv.app.fq.controller.Control;

/**
 *
 * @author bnavarro
 */
public class JPListarSesionesJuego extends javax.swing.JPanel {

    private final MedicoBo medico;
    private final PacienteBo paciente;

    /**
     * Creates new form panel1
     *
     * @param medico
     * @param paciente
     */
    public JPListarSesionesJuego(MedicoBo medico, PacienteBo paciente) {
        initComponents();
        this.medico = medico;
        this.paciente = paciente;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelControles = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePacientes = new javax.swing.JTable();
        lblNombrePaciente = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        jPanelControles.setBackground(new java.awt.Color(51, 51, 51));
        jPanelControles.setLayout(new java.awt.GridBagLayout());

        jTablePacientes.setBackground(new java.awt.Color(51, 51, 51));
        jTablePacientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTablePacientes.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        jTablePacientes.setForeground(new java.awt.Color(255, 255, 255));
        jTablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01/09/2019", "09:00 AM", "16 min"},
                {"01/09/2019", "14:00 PM", "32 min"},
                {"01/09/2019", "19:00 PM", "17 min"},
                {"02/09/2019", "08:00 AM", "35 min"},
                {"02/09/2019", "10:00 AM", "1:15hrs"},
                {"02/09/2019", "12:00 PM", "30 min"},
                {"02/09/2019", "14:00 PM", "15 min"},
                {"02/09/2019", "17:00 PM", "19 min"},
                {"02/09/2019", "19:00 PM", "29 min"},
                {"03/09/2019", "09:00 AM", "25 min"},
                {"03/09/2019", "14:00 AM", "18 min"},
                {"03/09/2019", "18:00 AM", "43 min"},
				{"04/09/2019", "09:00 AM", "16 min"},
                {"04/09/2019", "14:00 PM", "32 min"},
                {"04/09/2019", "19:00 PM", "17 min"},
                {"05/09/2019", "08:00 AM", "35 min"},
                {"05/09/2019", "10:00 AM", "1:15hrs"},
                {"05/09/2019", "12:00 PM", "30 min"},
                {"05/09/2019", "14:00 PM", "15 min"},
                {"05/09/2019", "17:00 PM", "19 min"},
                {"05/09/2019", "19:00 PM", "29 min"},
                {"06/09/2019", "09:00 AM", "25 min"},
                {"06/09/2019", "14:00 AM", "18 min"},
                {"06/09/2019", "18:00 AM", "43 min"},
				{"07/09/2019", "09:00 AM", "16 min"},
                {"07/09/2019", "14:00 PM", "32 min"},
                {"07/09/2019", "19:00 PM", "17 min"},
                {"08/09/2019", "08:00 AM", "35 min"},
                {"08/09/2019", "10:00 AM", "1:15hrs"},
                {"08/09/2019", "12:00 PM", "30 min"},
                {"08/09/2019", "14:00 PM", "15 min"},
                {"08/09/2019", "17:00 PM", "19 min"},
                {"08/09/2019", "19:00 PM", "29 min"},
                {"09/09/2019", "09:00 AM", "25 min"},
                {"09/09/2019", "14:00 AM", "18 min"},
                {"09/09/2019", "18:00 AM", "43 min"}
            },
            new String [] {
                "Fecha Conexión", "Hora Conexión", "Tiempo duración juego"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePacientes.setMinimumSize(new java.awt.Dimension(120, 0));
        jTablePacientes.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTablePacientes.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTablePacientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTablePacientes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 11);
        jPanelControles.add(jScrollPane2, gridBagConstraints);

        lblNombrePaciente.setBackground(new java.awt.Color(0, 0, 0));
        lblNombrePaciente.setFont(new java.awt.Font("Arial Unicode MS", 3, 18)); // NOI18N
        lblNombrePaciente.setForeground(new java.awt.Color(255, 255, 255));
        lblNombrePaciente.setText("Sesiones Juego");
        lblNombrePaciente.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 458;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanelControles.add(lblNombrePaciente, gridBagConstraints);

        btnVolver.setText("Volver");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 460, 34, 0);
        jPanelControles.add(btnVolver, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelControles, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelControles, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        jPanelControles.removeAll();
        jPanelControles.repaint();
        jPanelControles.revalidate();

//        JPPerfilPaciente panel = new JPPerfilPaciente(paciente, medico);
//        jPanelControles.add(panel);
//        jPanelControles.repaint();
//        jPanelControles.revalidate();

    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanelControles;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePacientes;
    private javax.swing.JLabel lblNombrePaciente;
    // End of variables declaration//GEN-END:variables
}
