/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.uv.app.fq.init;

import cl.uv.app.fq.bo.ControlBo;
import cl.uv.app.fq.bo.MedicoBo;
import cl.uv.app.fq.bo.PacienteBo;
import cl.uv.app.fq.controller.Control;
import cl.uv.app.fq.resource.ResourcesUtil;
import com.placeholder.PlaceHolder;
import java.awt.HeadlessException;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author bnavarro
 */
public class JPRegistroControlPaciente extends javax.swing.JPanel {

    private PacienteBo paciente;
    private MedicoBo medico;

    /**
     * Creates new form panel1
     */
    public JPRegistroControlPaciente(PacienteBo paciente, MedicoBo medico) {
        initComponents();
        this.paciente = paciente;
        this.medico = medico;
        cargarLabel();
        PlaceHolder holder = new PlaceHolder(jSpinnerEstatura, "000.0");
        holder = new PlaceHolder(jSpinnerPeso, "00.0");
        holder = new PlaceHolder(textAreaComentario, "Escriba un comentario...");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        JPanelRegistroControlPaciente = new javax.swing.JPanel();
        btnGuardarControl = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaComentario = new javax.swing.JTextArea();
        lblNombrePaciente7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTop = new javax.swing.JLabel();
        lblnm = new javax.swing.JLabel();
        jSpinnerPeso = new javax.swing.JTextField();
        jSpinnerEstatura = new javax.swing.JTextField();
        lblFechaNacimiento1 = new javax.swing.JLabel();
        lblFechaNacimiento2 = new javax.swing.JLabel();
        lblFechaNacimiento5 = new javax.swing.JLabel();
        jDataFechaControl = new com.toedter.calendar.JDateChooser();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelRegistroControlPaciente.setBackground(new java.awt.Color(255, 255, 255));
        JPanelRegistroControlPaciente.setLayout(new java.awt.GridBagLayout());

        btnGuardarControl.setBackground(new java.awt.Color(102, 102, 102));
        btnGuardarControl.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        btnGuardarControl.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarControl.setText("Sesion Soplado");
        btnGuardarControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarControl.setMaximumSize(new java.awt.Dimension(120, 29));
        btnGuardarControl.setMinimumSize(new java.awt.Dimension(120, 29));
        btnGuardarControl.setPreferredSize(new java.awt.Dimension(150, 29));
        btnGuardarControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarControlActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 18, 200, 0);
        JPanelRegistroControlPaciente.add(btnGuardarControl, gridBagConstraints);

        textAreaComentario.setColumns(20);
        textAreaComentario.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        textAreaComentario.setLineWrap(true);
        textAreaComentario.setRows(5);
        textAreaComentario.setText("\n");
        jScrollPane1.setViewportView(textAreaComentario);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 0, 30);
        JPanelRegistroControlPaciente.add(jScrollPane1, gridBagConstraints);

        lblNombrePaciente7.setBackground(new java.awt.Color(0, 0, 0));
        lblNombrePaciente7.setFont(new java.awt.Font("Arial Unicode MS", 2, 14)); // NOI18N
        lblNombrePaciente7.setForeground(new java.awt.Color(0, 0, 0));
        lblNombrePaciente7.setText("Comentarios: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 37;
        gridBagConstraints.ipadx = 249;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 18, 0, 0);
        JPanelRegistroControlPaciente.add(lblNombrePaciente7, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/uv/app/fq/resource/siluetaPerfil.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 9, 0, 0);
        JPanelRegistroControlPaciente.add(jLabel1, gridBagConstraints);

        lblTop.setBackground(new java.awt.Color(0, 0, 0));
        lblTop.setFont(new java.awt.Font("Arial Unicode MS", 3, 18)); // NOI18N
        lblTop.setForeground(new java.awt.Color(255, 255, 255));
        lblTop.setText("  Control Hospitalario");
        lblTop.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 43;
        gridBagConstraints.ipadx = 369;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        JPanelRegistroControlPaciente.add(lblTop, gridBagConstraints);

        lblnm.setBackground(new java.awt.Color(0, 0, 0));
        lblnm.setFont(new java.awt.Font("Arial Unicode MS", 2, 14)); // NOI18N
        lblnm.setForeground(new java.awt.Color(0, 0, 0));
        lblnm.setText("Nombre Paciente: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.ipadx = 350;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 18, 0, 0);
        JPanelRegistroControlPaciente.add(lblnm, gridBagConstraints);

        jSpinnerPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSpinnerPesoActionPerformed(evt);
            }
        });
        jSpinnerPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jSpinnerPesoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 46;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 3, 0, 0);
        JPanelRegistroControlPaciente.add(jSpinnerPeso, gridBagConstraints);

        jSpinnerEstatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jSpinnerEstaturaKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 46;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 3, 0, 0);
        JPanelRegistroControlPaciente.add(jSpinnerEstatura, gridBagConstraints);

        lblFechaNacimiento1.setBackground(new java.awt.Color(0, 0, 0));
        lblFechaNacimiento1.setFont(new java.awt.Font("Arial Unicode MS", 2, 14)); // NOI18N
        lblFechaNacimiento1.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaNacimiento1.setText("Peso (Kl):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 18, 0, 0);
        JPanelRegistroControlPaciente.add(lblFechaNacimiento1, gridBagConstraints);

        lblFechaNacimiento2.setBackground(new java.awt.Color(0, 0, 0));
        lblFechaNacimiento2.setFont(new java.awt.Font("Arial Unicode MS", 2, 14)); // NOI18N
        lblFechaNacimiento2.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaNacimiento2.setText("Estatura (Cm):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 18, 0, 0);
        JPanelRegistroControlPaciente.add(lblFechaNacimiento2, gridBagConstraints);

        lblFechaNacimiento5.setBackground(new java.awt.Color(0, 0, 0));
        lblFechaNacimiento5.setFont(new java.awt.Font("Arial Unicode MS", 2, 14)); // NOI18N
        lblFechaNacimiento5.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaNacimiento5.setText("Fecha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 0, 0);
        JPanelRegistroControlPaciente.add(lblFechaNacimiento5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 0, 0);
        JPanelRegistroControlPaciente.add(jDataFechaControl, gridBagConstraints);

        add(JPanelRegistroControlPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarControlActionPerformed
        ResourcesUtil rutil = new ResourcesUtil();
        System.out.println("textAreaComentario: "+textAreaComentario.getText()+".");
        if (jSpinnerEstatura.getText().equals("000.0") || jSpinnerPeso.getText().equals("00.0") || textAreaComentario.getText().equals("Escriba un comentario...")) {
            JOptionPane.showMessageDialog(null, "Llene formulario antes de continuar", "Información:", 0, new ImageIcon(rutil.getPulmonShowMessage()));

        } else {
            try {
                ControlBo controlBo = new ControlBo();

                Date fechaControl = jDataFechaControl.getDate();
                float peso = Float.parseFloat(jSpinnerPeso.getText());
                float estatura = Float.parseFloat(jSpinnerEstatura.getText());
                String comentario = textAreaComentario.getText();

                controlBo.setFechaControl(fechaControl);
                controlBo.setEstatura(estatura);
                controlBo.setPeso(peso);
                controlBo.setComentario(comentario);
                controlBo.setPacienteIdPaciente(paciente.getIdPaciente());
                controlBo.setMedioIdMedico(medico.getIdMedico());
//            Control controlController = new Control();
//            if (controlController.insertControl(controlBo, medico, paciente) == 1) {
//            JOptionPane.showMessageDialog(null, "Control Iniciado exitosamente!.", "Información:", 0, new ImageIcon(rutil.getPulmonShowMessage()));
                JPanelRegistroControlPaciente.removeAll();
                JPanelRegistroControlPaciente.repaint();
                JPanelRegistroControlPaciente.revalidate();

                JPRegistroSesionSoplado panel = new JPRegistroSesionSoplado(controlBo, paciente, medico);
                JPanelRegistroControlPaciente.add(panel);
                JPanelRegistroControlPaciente.repaint();
                JPanelRegistroControlPaciente.revalidate();
//            } else {
//                JOptionPane.showMessageDialog(null, "Control no se ha podido iniciar.", "Información:", 0, new ImageIcon(rutil.getPulmonShowMessage()));

//            }
            } catch (NumberFormatException numberFormatException) {
                JOptionPane.showMessageDialog(null, "Control no se ha podido iniciar.\nFormato de números inválido", "Información:", 0, new ImageIcon(rutil.getPulmonShowMessage()));

            } catch (HeadlessException headlessException) {
                JOptionPane.showMessageDialog(null, "Control no se ha podido iniciar.", "Información:", 0, new ImageIcon(rutil.getPulmonShowMessage()));

            }
        }


    }//GEN-LAST:event_btnGuardarControlActionPerformed

    private void jSpinnerPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSpinnerPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinnerPesoActionPerformed

    private void jSpinnerPesoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerPesoKeyReleased
        String[] v = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "."};
        char c = evt.getKeyChar();
        String s = "%" + c;
        s = s.replace("%", "");
        if (s.equals(v[0]) || s.equals(v[1]) || s.equals(v[2]) || s.equals(v[3]) || s.equals(v[4]) || s.equals(v[5])) {
        } else if (s.equals(v[6]) || s.equals(v[7]) || s.equals(v[8]) || s.equals(v[9]) || s.equals(v[10])) {
        } else {
            int k = jSpinnerPeso.getText().length() - 1;
            String n = jSpinnerPeso.getText().substring(0, k);
            jSpinnerPeso.setText(n);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinnerPesoKeyReleased

    private void jSpinnerEstaturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerEstaturaKeyReleased
        String[] v = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "."};
        char c = evt.getKeyChar();
        String s = "%" + c;
        s = s.replace("%", "");
        if (s.equals(v[0]) || s.equals(v[1]) || s.equals(v[2]) || s.equals(v[3]) || s.equals(v[4]) || s.equals(v[5])) {
        } else if (s.equals(v[6]) || s.equals(v[7]) || s.equals(v[8]) || s.equals(v[9]) || s.equals(v[10])) {
        } else {
            int k = jSpinnerEstatura.getText().length() - 1;
            String n = jSpinnerEstatura.getText().substring(0, k);
            jSpinnerEstatura.setText(n);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jSpinnerEstaturaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelRegistroControlPaciente;
    private javax.swing.JButton btnGuardarControl;
    private com.toedter.calendar.JDateChooser jDataFechaControl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSpinnerEstatura;
    private javax.swing.JTextField jSpinnerPeso;
    private javax.swing.JLabel lblFechaNacimiento1;
    private javax.swing.JLabel lblFechaNacimiento2;
    private javax.swing.JLabel lblFechaNacimiento5;
    private javax.swing.JLabel lblNombrePaciente7;
    private javax.swing.JLabel lblTop;
    private javax.swing.JLabel lblnm;
    private javax.swing.JTextArea textAreaComentario;
    // End of variables declaration//GEN-END:variables

    private void cargarLabel() {
        lblnm.setText("Nombre Paciente: " + paciente.getNombre());

    }

    private int getEdad(String edad) {
        System.out.println(edad);
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate fechaNac = LocalDate.parse(edad, fmt);
        LocalDate ahora = LocalDate.now();
        Period periodo = Period.between(fechaNac, ahora);

        return periodo.getYears();
    }
}
